typography_spectrum: 0.7033828042913228
color:
  brandColors:
    - '#fefefe'
    - '#2a7f72'
    - '#2bb9a7'
    - '#82cec7'
    - '#cce9e8'
  brandStrength: 0.775598730193451
  lightness: 0.533719600411132
  saturation: 0.6875
  rhythmicContrast: 0.8411432767752558
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.9112
analytics:
  google: null
  facebook: null
  twitter: null
name: EPSportsTherapy
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Ed Pratt Sports Therapy
description: Professional Sports Therapy & Sports Massage
purpose: []
